# Generated by Django 5.2.1 on 2025-05-28 12:19

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import myApp.utils.upload_pather
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('events', '0001_initial'), ('events', '0002_alter_event_options_event_is_archived_and_more'), ('events', '0003_event_is_pinned'), ('events', '0004_event_image'), ('events', '0005_event_city')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=100, verbose_name='nazwa wydarzenia')),
                ('event_date', models.DateTimeField(verbose_name='data wydarzenia')),
                ('location', models.CharField(max_length=100, verbose_name='miejsce wydarzenia')),
                ('description', models.TextField(max_length=500, verbose_name='opis wydarzenia')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='data stworzenia wydarzenia')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='data edycji wydarzenia')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='twórca wydarzenia')),
                ('is_archived', models.BooleanField(default=False, verbose_name='czy archiwalne')),
                ('is_verified', models.BooleanField(default=False, verbose_name='czy zweryfikowane')),
                ('is_pinned', models.BooleanField(default=False, verbose_name='czy przypięte')),
                ('image', models.ImageField(blank=True, upload_to=myApp.utils.upload_pather.dynamic_image_upload_pather, verbose_name='zdjęcie wydarzenia')),
                ('city', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='miasto wydarzenia')),
            ],
            options={
                'verbose_name': 'Wydarzenie',
                'verbose_name_plural': 'Wydarzenia',
            },
        ),
    ]
