# Generated by Django 5.2.3 on 2025-06-10 15:12

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_squashed_0005_event_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='city',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, help_text='<br>', null=True, srid=4326, verbose_name='miejsce wydarzenia'),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(max_length=100, verbose_name='miasto wydarzenia'),
        ),
    ]
