# Generated by Django 5.2.1 on 2025-05-20 15:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Poll",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.TextField(verbose_name="pytanie ankiety")),
                (
                    "creation_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="data utworzenia"
                    ),
                ),
                (
                    "end_date",
                    models.DateTimeField(verbose_name="data zamknięcia"),
                ),
                (
                    "archive_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="data archiwizacji"
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="twórca ankiety",
                    ),
                ),
            ],
            options={
                "verbose_name": "ankieta",
                "verbose_name_plural": "ankiety",
            },
        ),
        migrations.CreateModel(
            name="Choice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "text",
                    models.CharField(
                        max_length=200, verbose_name="reprezentacja opcji"
                    ),
                ),
                (
                    "poll",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="choices",
                        to="polls.poll",
                        verbose_name="ankieta",
                    ),
                ),
            ],
            options={
                "verbose_name": "wybór",
                "verbose_name_plural": "wybory",
            },
        ),
        migrations.CreateModel(
            name="Vote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "vote_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="data zagłosowania"
                    ),
                ),
                (
                    "choice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="polls.choice",
                        verbose_name="decyzja",
                    ),
                ),
                (
                    "poll",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="polls.poll",
                        verbose_name="ankieta",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="głosujący",
                    ),
                ),
            ],
            options={
                "verbose_name": "głos",
                "verbose_name_plural": "głosy",
                "indexes": [
                    models.Index(
                        fields=["poll"], name="polls_vote_poll_id_cee50f_idx"
                    ),
                    models.Index(
                        fields=["choice"], name="polls_vote_choice__c1d655_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("poll", "user"), name="unique_user_vote"
                    )
                ],
            },
        ),
    ]
