# Generated by Django 5.2.1 on 2025-05-28 12:10

import django.db.models.deletion
import myApp.utils.upload_pather
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo_gallery', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='tytuł galerii')),
                ('description', models.TextField(max_length=500, verbose_name='opis galerii')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('thumbnail', models.ImageField(upload_to=myApp.utils.upload_pather.dynamic_image_upload_pather, verbose_name='miniaturka galerii')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='twórca galerii')),
            ],
            options={
                'verbose_name': 'Galeria',
                'verbose_name_plural': 'Galerie',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='tytuł zdjęcia')),
                ('image', models.ImageField(upload_to=myApp.utils.upload_pather.dynamic_image_upload_pather)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='photo_gallery.gallery')),
            ],
            options={
                'verbose_name': 'Zdjęcie',
                'verbose_name_plural': 'Zdjęcia',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.DeleteModel(
            name='Announcement',
        ),
    ]
