name: projekt-testowy

services:
  app:
    build:
      context: .
    container_name: app
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - media_volume:/app/src/media/
      - static_volume:/app/src/static/
    environment:
      - PYTHONPATH=/app/src
    networks:
      - backend
    depends_on:
      - db
      - redis

  celery:
    build:
      context: .
    container_name: celery
    command: celery -A myApp worker --loglevel=info
    volumes:
      - .:/app
    environment:
      - PYTHONPATH=/app/src
    networks:
      - backend
    depends_on:
      - app
      - redis

  celery-beat:
    build:
      context: .
    container_name: celery_beat
    command: celery -A myApp beat --loglevel=info
    volumes:
      - .:/app
    environment:
      - PYTHONPATH=/app/src
    networks:
      - backend
    depends_on:
      - app
      - redis

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - backend

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - media_volume:/app/src/media/
      - static_volume:/app/src/static/
    networks:
      - backend
    depends_on:
      - app

  db:
    image: postgis/postgis:17-3.5-alpine
    container_name: db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

networks:
  backend:

volumes:
  postgres_data:
  media_volume:
  static_volume:
