# Generated by Django 5.2.1 on 2025-05-10 19:18


import django.db.models.deletion
import myApp.utils.upload_pather
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='tytuł ogłoszenia')),
                ('place', models.CharField(max_length=50, verbose_name='miejsce z ogłoszenia')),
                ('rooms', models.PositiveIntegerField(verbose_name='ilość pokoi')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='cena wynajmu')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='data utworzenia ogłoszenia')),
                ('description', models.TextField(verbose_name='opis ogłoszenia')),
                ('banner', models.ImageField(blank=True, upload_to=myApp.utils.upload_pather.dynamic_image_upload_pather, verbose_name='zdjęcie ogłoszenia')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='twórca ogłoszenia')),
            ],
            options={
                'verbose_name': 'ogłoszenie',
                'verbose_name_plural': 'ogłoszenia',
            },
        ),
    ]