# Generated by Django 5.2.1 on 2025-05-19 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='archive_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='data archiwizacji'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='status weryfikacji'),
        ),
    ]
