# Generated by Django 5.2.1 on 2025-05-28 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0002_announcement_archive_date_announcement_is_verified'),
        ('announcements', '0002_announcement_is_pinned'),
    ]

    operations = [
    ]
