# Generated by Django 5.2.1 on 2025-05-15 16:37

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('comments_and_ratings', '0001_initial'), ('comments_and_ratings', '0002_alter_rating_rating'), ('comments_and_ratings', '0003_alter_rating_rating')]

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(verbose_name='id komentarza')),
                ('content', models.TextField(max_length=500, verbose_name='treść komentarza')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='data utworzenia komentarza')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='data edycji komentarza')),
                ('is_active', models.BooleanField(default=True, verbose_name='czy aktywny')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='zawartosc do komentowania')),
                ('parent_comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='comments_and_ratings.comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name="oceniajacy uzytkownik")),
            ],
            options={
                'verbose_name': 'Komentarz',
                'verbose_name_plural': 'Komentarze',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(verbose_name='id oceny')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='ocena')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='data utworzenia oceny')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='data edycji oceny')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='zawartosc do oceny')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to=settings.AUTH_USER_MODEL, verbose_name="oceniajacy uzytkownik")),
            ],
            options={
                'verbose_name': 'Ocena',
                'verbose_name_plural': 'Oceny',
                'unique_together': {('content_type', 'object_id', 'user')},
            },
        ),
    ]
